#!/usr/bin/env bash 

IFS='
'

#
# written by: David Scott
# date      : 01/21/2024
#


if [ "$1" == "" ]; then
        echo "$(basename "$0"): Directory ..."
        exit -1
fi


# iterate through the directories to apply 

for dir in $@
do

        pushd . > /dev/null 2>&1
        echo -e "processing ${dir}\n"
        cd ${dir}

        #
        # in theory there should only be 1 json file but occasionally I run this on an upper level dir so be sure
        #
        for x in $(find . -name *json)
        do
                echo -ne "${x}: "

                # don't want to overite the metadata file

                mv "${x}" "${x}-"

                #
                # set the explicit flag to false 
                #

		jq '.explicit = false' "${x}-" > "${x}"
                echo -e "done\n"
                rm ${x}-
        done
        popd > /dev/null 2>&1
done
